spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  application:
    name: EurekaGitService
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false